name: Aggregate issues for Instant Issues

on:
  push:
  schedule:
    # run every hour
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: instant-issues/action@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repos: |
               go-gitea/gitea
               haskell/cabal
               isaacs/github
               matrix-org/synapse
               microsoft/typescript
               microsoft/vscode
               nixos/nixpkgs
               rocketchat/rocket.chat
               vector-im/riot-web
               ytdl-org/youtube-dl
               zulip/zulip
               zulip/zulip-mobile
               zulip/zulip-terminal
