name: Aggregate issues for Instant Issues

on:
  push:
  schedule:
    # run every hour
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: instant-issues/action@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repos: |
               zulip/zulip
               zulip/zulip-mobile
               zulip/zulip-terminal
               go-gitea/gitea
               RocketChat/Rocket.Chat
               Microsoft/vscode
               ytdl-org/youtube-dl
